controller_manager:
  ros__parameters:
    update_rate: 80  # Hz

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
  ros__parameters:
    joints:
      - follower_joint1
      - follower_joint2
      - follower_joint3
      - follower_joint4
      - follower_joint5
      - follower_joint_gripper

joint_trajectory_controller:
  ros__parameters:
    joints:
      - follower_joint1
      - follower_joint2
      - follower_joint3
      - follower_joint4
      - follower_joint5
      - follower_joint_gripper

    command_interfaces:
      - position

    state_interfaces:
      - position
